vich_uploader:
    db_driver: orm
    mappings:
        upload:
            uri_prefix: /assets/upload/images/
            upload_destination: '%kernel.project_dir%/public/assets/upload/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
